### ISSUE TITLE
Bug: Can't set LED color via MIDI when Switch Action Type set to "Note Toggle" or "Note Hold"

### ISSUE THREAD

**Issue by supertwang** [DJ-TechTools/Midi_Fighter_Twister_Open_Source#5]
Hi y'all,
I've been enjoying my Twister immensely.  In putting it through its paces, I've found either a firmware bug, or a bug with the MacOs MidiFighter Utility.  

Here's how to duplicate: When an encoder's "Switch Action Type" is configured as Note Hold, it is no longer possible to set the LED color via MIDI (ie CC for the knob #-1, like 0 for knob 1, channel 2, values 1-126.  The color simply stays on the "On Color."  All of the other knob configuration via MIDI seems to work fine, just the LED color is unresponsive.

I'm hoping you'll patch this in an updated firmware release.  It is preventing me from coloring my knob sets though midi.

fwiw, I'm on macos 10.12 (sierra), on a mac book pro late 2013, 2.3ghz, running v2.75 of the MidiFighter Utility, with the 09 Mar 29018 Firmware.

Thanks for looking into this!
Best,
Dave

ps. wishlist... I wish I could set all of the settings in the utility via midi.  This would allow me to use a tool to expand the number of available knob sets.  Any chance you'd publish the sysex format to make these settings?  Thanks!

**Comment by wunnation** [comment]
Hi Supertwang,

I just tried it out and it's working for me under the same configuration.
Your firmware is up to date, so we are good there.
Perhaps the source of confusion is that the MIDI Feedback mapping moves, when you move the MIDI Output Mapping.

In my test, I remapped the top-left button as Note Hold (Note 0 Channel 2 by default), and row 2-left button as Note Toggle (Note 4 Channel 2 by default.)

To send MIDI Feedback to these buttons, the top-left is
Channel 2, Note 0 On, color_value (decimal: 145, 0, color_value) (hex: 0x91, 0x00, color_value)

- color_value = 0 means change to the  'Off Color' as assigned in MF Utility.
- color_value = 127 means change to the 'On Color' as assigned in MF Utility.
The rest of the values are divided up by color, and change pretty much with increases with 8 in velocity.

Some other quirks you should know about.
- MIDI Feedback Value overrides the declared "on" and "off" colors, unless the last MIDI Feedback value sent to the that control on the Twister was '0' or '127'.

Let us know if you need more help with this!

Sysex Format.
There's always a chance! I'll ask around.




So I remapped the
