### ISSUE TITLE
Banks don't work

### ISSUE THREAD

**Issue by bdesanmiguel** [DJ-TechTools/Midi_Fighter_Twister_Open_Source#7]
Using the 20191002 release code, banks don't work anymore i.e. banks 2-4 use/affect bank 1.

I believe it is due to the removal of [this](https://github.com/DJ-TechTools/Midi_Fighter_Twister_Open_Source/commit/e7fa9fe7017a2ba51f2240f81043a759e091ab4b/#diff-2558dc50c6a9f56f85ae014c4a6c9ca1L111) line.

**Comment by doodlebro** [comment]
This is definitely present in the current source code once built (debug and release), but I haven't been able to track down a sure cause yet. I had this issue when my MF Twister first came in, which was remedied only by reflashing the latest (20191002) firmware. I think this official firmware is alright, as I have tested this a few times. I will continue trying to build a version from source that is missing the bug.

**Comment by bdesanmiguel** [comment]
Hi @doodlebro, the cause is the the removal of the following line in encoders.c in e7fa9fe7017a2ba51f2240f81043a759e091ab4b:
`virtual_encoder_id += bank*16;`

Banks work as expected if you add this line back.

@eangolden is there any chance you can look into modifying the license as discussed here: #3? Using this issue as an example - I fixed it for myself at the time of posting. I did not make a pull request since per the license it is ambiguous as to whether that is permitted.
